export const LogSteps = [
	{
		selector: '[data-tour="my-requests"]',
		content: 'List of requests generated by current public key',
	},
	{
		selector: '[data-tour="my-contributions"]',
		content: 'List of contributed requests that angle submitted file.',
	},
	{
		selector: '',
		content:
			'Well done! You earn 100 BBits for this learning! want to earn more? learn every guide on pages and collect about 500 BBits!',
	},
];
