services:
  zarela-webapp:
    container_name: zarela-webapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_ZARELA_CONTRACT_ADDRESS=${REACT_APP_ZARELA_CONTRACT_ADDRESS}
        - REACT_APP_ETHERSCAN_MAINNET_API_LINK=${REACT_APP_ETHERSCAN_MAINNET_API_LINK}
        - REACT_APP_ETHEREUM_API_KEY=${REACT_APP_ETHEREUM_API_KEY}
        - REACT_APP_IPFS=${REACT_APP_IPFS}
        - REACT_APP_IPFS_GET_LINK=${REACT_APP_IPFS_GET_LINK}
        - REACT_APP_PINATA_JWT=${REACT_APP_PINATA_JWT}
        - REACT_APP_ETHERSCAN_LINK=${REACT_APP_ETHERSCAN_LINK:-https://etherscan.io/tx/}
        - REACT_APP_ZARELA_BUSINESS_CATEGORY=${REACT_APP_ZARELA_BUSINESS_CATEGORY:-1}
        - REACT_APP_EXPLORE_LINK=${REACT_APP_EXPLORE_LINK}
        - DISABLE_ESLINT_PLUGIN=true
    image: zarela-webapp:latest
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
    networks:
      - zarela-network

networks:
  zarela-network:
    driver: bridge
    name: zarela-network
