export const actionTypes = {
	SET_FALLBACK_WEB3: 'SET_FALLBACK_WEB3',
	SET_CONTRACT: 'SET_CONTRACT',
	SET_BBIT_BALANCE: 'SET_BBIT_BALANCE',
	SET_ETHER_BALANCE: 'SET_ETHER_BALANCE',
	SET_GAS: 'SET_GAS',
	SET_ZARELA_CURRENT_DAY: 'SET_ZARELA_CURRENT_DAY',
	SET_ERROR: 'SET_ERROR',
	SET_CLIENT_DEVICE: 'SET_CLIENT_DEVICE',
	SET_GUIDE_IS_OPEN: 'SET_GUIDE_IS_OPEN',
};
