export const actionTypes = {
	SET_FALLBACK_WEB3: 'SET_FALLBACK_WEB3',
	SET_ZARELA_BANK: 'SET_ZARELA_BANK',
	SET_CONTRACT: 'SET_CONTRACT',
	SET_BBIT_BALANCE: 'SET_BBIT_BALANCE',
	SET_ETHER_BALANCE: 'SET_ETHER_BALANCE',
	SET_GAS: 'SET_GAS',
	SET_ERROR: 'SET_ERROR',
	SET_ZARELA_INIT_DATE: 'SET_ZARELA_INIT_DATE',
	SET_ZARELA_DAILY_GIFT: 'SET_ZARELA_DAILY_GIFT',
}